### ISSUE TITLE
Review of initial commits

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/docker-sbt-node-mongo#1]
As the development of sbt-docker-images started from :zero:, I just pushed to master. The current version should be viewed as stable and only be changed through reviewed PR.
This first version also needs to be reviewed. Thanks :whale:

**Comment by twerkmeister** [comment]
Great Job, very clean, and nice documentation! 
I created a pull request for a change of the documentation wording. Additionally, it would be great to have an example for the docker compose file that allows to get rid of the volume mounts and to connect the mongo container.

**Comment by jstriebel** [comment]
The readme-changes are perfect, thanks! I added issue #3 for the docker-compose example.
